version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: trading-postgres
    environment:
      POSTGRES_DB: trading_db
      POSTGRES_USER: trading_user
      POSTGRES_PASSWORD: trading_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - trading-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: trading-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - trading-network

  # AI Service
  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    container_name: trading-ai-service
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://trading_user:trading_password@postgres:5432/trading_db
      - REDIS_URL=redis://redis:6379
      - SIGNAL_THRESHOLD=0.8
      - MAX_POSITION_PERCENT=1.0
    depends_on:
      - postgres
      - redis
    networks:
      - trading-network

  # Data Service
  data-service:
    build:
      context: ./data-service
      dockerfile: Dockerfile
    container_name: trading-data-service
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY:-demo}
      - NEWS_API_KEY=${NEWS_API_KEY:-demo}
      - IEX_API_KEY=${IEX_API_KEY:-demo}
    depends_on:
      - redis
    networks:
      - trading-network

volumes:
  postgres_data:
  redis_data:

networks:
  trading-network:
    driver: bridge
